syntax = "proto3";

package chat;

service ChatService {
  rpc SendSystemMessage (RoomMessageRequest) returns (MessageResponse);
  rpc EnforceChatBlock (RoomRequest) returns (RoomResponse);
  rpc BlockUserRooms (UserRequest) returns (BlockResponse);
}

message RoomRequest {
  string roomId = 1;
}

message RoomMessageRequest {
  string roomId = 1;
  string content = 2;
}

message MessageResponse {
  string id = 1;
  string roomId = 2;
  string content = 3;
}

message RoomResponse {
  string roomId = 1;
  bool isBlocked = 2;
}

message UserRequest {
  string userId = 1;
}

message BlockResponse {
  int32 blockedCount = 1;
}
